#!/usr/bin/python3
import sys


def factorize(num):
    """Factorize the given number into a product of two smaller number """
    fnum = 2
    j = 2 ** 23
    while num % fnum:
        if num % j == 0:
            fnum = j
            break
        fnum += 1
        j += 1

    snum = num // fnum
    return (snum, fnum)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(f"Wrong usage: {sys.argv[0]} <file_path>")
    file = open(sys.argv[1], 'r')
    lines = file.readlines()

    for line in lines:
        num = int(line.rstrip())
        snum, fnum = factorize(num)
        print(f"{num}={snum}*{fnum}")
